version: '3.8'

services:
  backend:
    build: ./backend
    container_name: web-app-backend
    volumes:
      - ./backend:/app
      - ./openapi:/openapi
      - chroma-data:/app/chroma_data
      - ./sample_data:/sample_data
    ports:
      - "5001:5000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    networks:
      - web-app-network
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: web-app-frontend
    volumes:
      - ./frontend:/app
      - ./openapi:/openapi
    ports:      
      - "3050:3000"
    environment:
      - OPENAPI_SPEC_PATH=/openapi/openapi.yml
      - VITE_API_URL=http://localhost:5001
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

networks:
  web-app-network:
    driver: bridge
    name: web-app-network

volumes:
  frontend-node-modules:
  chroma-data: 