openapi: 3.0.0
info:
  title: Legal Document Analysis API
  description: API for analyzing legal documents
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local development server
paths:
  /upload:
    post:
      summary: Upload a document for analysis
      description: Upload a file and receive a UUID for tracking the analysis
      operationId: uploadDocument
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The file to upload
      responses:
        '201':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          description: Bad request
  /analysis/{analysisId}:
    get:
      summary: Get analysis results
      description: Retrieve analysis results for a document using its UUID
      operationId: getAnalysisById
      parameters:
        - name: analysisId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '404':
          description: Analysis not found
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "Task title"
        description:
          type: string
          example: "Task description"
        completed:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - title
        - completed
    NewItem:
      type: object
      properties:
        title:
          type: string
          example: "Task title"
        description:
          type: string
          example: "Task description"
        completed:
          type: boolean
          example: false
      required:
        - title
    UploadResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        message:
          type: string
          example: "File uploaded successfully"
      required:
        - id
    AnalysisItem:
      type: object
      properties:
        text:
          type: string
          example: "Der Vertrag verlängert sich automatisch um weitere 12 Monate."
        category:
          type: string
          enum: [fehlend, ungewöhnlich, nichtig]
          example: "ungewöhnlich"
        description:
          type: string
          example: "Automatische Verlängerungsklausel mit ungewöhnlich langer Dauer"
      required:
        - text
        - category
    AnalysisResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        results:
          type: array
          items:
            $ref: '#/components/schemas/AnalysisItem'
      required:
        - id
        - results 